#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

axi_lcd-y := axi_lcd_encoder.o axi_lcd_crtc.o axi_lcd_drv.o

obj-$(CONFIG_DRM_AXI_LCD) += axi_lcd.o
